# Gunakan Node.js versi LTS
FROM node:20

# Buat folder kerja
WORKDIR /app

# Salin package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin semua file backend
COPY . .

# Ekspos port backend
EXPOSE 5000

# Jalankan server
CMD ["node", "index.js"]
